sudo: required

language: generic

script:
jobs:
  include:
    - stage: "build and test"
      name: "CentOS6 and CentOS7"
      script:
        - cd $TRAVIS_BUILD_DIR/docker && ./build_one.sh centos
