sudo: required

language: generic

script:
jobs:
  include:
    - stage: "build and test"
      name: "CentOS6"
      script:
        - cd $TRAVIS_BUILD_DIR/docker/CentOS6 && ./dockit
    - stage: "build and test"
      name: "CentOS7"
      script:
        - cd $TRAVIS_BUILD_DIR/docker/CentOS && ./dockit centos7
