sudo: required

language: generic

script:
jobs:
  include:
    - stage: "build and test"
      name: "Debian 9 (stretch)"
      script:
        - cp $TRAVIS_BUILD_DIR/docker/dockerfiles/debian/9/Dockerfile .
        - cp $TRAVIS_BUILD_DIR/docker/dockerfiles/debian/9/timezone .
        - docker build .
