sudo: required

language: generic

script:
jobs:
  include:
    - stage: build
      name: debian
      matrix:
        include:
          - version: 9
            script:
              - cp $TRAVIS_BUILD_DIR/docker/dockerfiles/debian/$version/Dockerfile .
              - cp $TRAVIS_BUILD_DIR/docker/dockerfiles/debian/$version/timezone .
              - docker build .
